#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username GID homeDir commandOrShell UID password UIDInfo ; do
	echo 'The user "$username" is part of the "$GUID" gang, lives in "$homeDir" and rides "$commandOrShell". "$UID"\'s place is protected by the passcode "$password", more info about the user here: "$UIDInfo"'
done < "/etc/passwd"
