#!/usr/bin/env bash
#This script prints 'Hi' on the 9th iteration
count=0
word=''
while ((count < 10 ))
do
	if (( count == 8)); then
		word='Hi'
		echo $word
		((count++))
	else
		word='Best School'
		echo $word
		((count++))
	fi
done
