#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
minute=1

echo "Hour: 0"
while ((hour <= 12 ))
do 
	while ((minute <= 60 ))
	do
		if (( minute == 60)); then
			((hour++))
			echo "Hour: $hour"
			minute=1
		else 
			echo "$minute"
			((minute++))
		fi
	done
done
