#!/usr/bin/env bash
# a script that creates /var/run/myscript.pid containing its PID, displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


echo $$ > /var/run/myscript.pid

handle_sigterm(){
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 0
}

handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
	echo "Received SIGQUIT signal. Initiating graceful shutdown."
	rm -f /var/run/myscript.pid
	exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
